name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Test
        if: contains(github.event.pull_request.labels.*.name, 'stage')
        run: echo "Test from branch"